# mkdocs.yml
site_name: "Machine Learning Notes"
site_description: "My ML notes, cheatsheets, and experiments"
site_url: https://adityachauhan0.github.io/amazon-ml/
repo_url: https://github.com/adityachauhan0/amazon-ml
repo_name: adityachauhan0/amazon-ml
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

# Optional: show last updated time (requires plugin below)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adityachauhan0
      name: GitHub

nav:
  - Home: index.md
  - Notes:
      - "Supervised Learning": notes/supervised.md
      - "Unsupervised Learning": notes/unsupervised.md
      - "Deep Learning": notes/deep-learning.md
      - "NLP": notes/nlp.md
  - Cheatsheets: cheatsheets/index.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  # Core niceties
  - admonition
  - def_list
  - footnotes
  - attr_list
  - toc:
      permalink: true

  # Code, tabs, task lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

  # Details + collapsibles
  - pymdownx.details

  # Mermaid diagrams (```mermaid fences)
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Math (KaTeX via arithmatex)
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # Mermaid (diagrams)
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  # KaTeX (math) + auto-render
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  # Initialize KaTeX after page loads
  - js/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

# Where your docs live
docs_dir: docs
